name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on Ubuntu runner

    steps:
      - uses: actions/checkout@v3  # Checkout code from repository

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16  # You can adjust the Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run predeploy

      - name: Deploy to GitHub Pages
        uses: omkartapale/react-deployment-gh-pages@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Access token with deploy permissions
          GIT_USER_EMAIL: "mss.pradeepkumar@gmail.com"  # Optional: Set deployer email
          GIT_USER_NAME: "pradeepkumarpop"  # Optional: Set deployer name

